services:
  - type: web
    name: finguardai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FRONTEND_URL
        value: https://finguardai.vercel.app
    healthCheckPath: /health
    autoDeploy: true
